name: WTMux
options:
  bundleIdPrefix: com.grahampark
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  WTCore:
    path: Packages/WTCore
  WTTransport:
    path: Packages/WTTransport
  WTGit:
    path: Packages/WTGit
  WTProcess:
    path: Packages/WTProcess
  WTTerminal:
    path: Packages/WTTerminal
  WTDiff:
    path: Packages/WTDiff

targets:
  WTMux:
    type: application
    platform: macOS
    sources:
      - path: WTMux
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grahampark.wtmux
        WTMUX_DISPLAY_NAME: WTMux Dev
        WTMUX_STORE_NAME: WTMux
        WTMUX_URL_SCHEME: wtmux
        WTMUX_MCP_SERVER_NAME: wtmux
        WTMUX_NOTIFICATION_PREFIX: com.grahampark.wtmux
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 6.0
        ENABLE_PREVIEWS: YES
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        SWIFT_STRICT_CONCURRENCY: complete
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        COMBINE_HIDPI_IMAGES: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: WTCore
      - package: WTTransport
      - package: WTGit
      - package: WTProcess
      - package: WTTerminal
      - package: WTDiff
    info:
      path: WTMux/Info.plist
      properties:
        CFBundleIconFile: AppIcon
        CFBundleName: $(WTMUX_DISPLAY_NAME)
        CFBundleDisplayName: $(WTMUX_DISPLAY_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSApplicationCategoryType: public.app-category.developer-tools
        WTMuxStoreName: $(WTMUX_STORE_NAME)
        WTMuxMCPServerName: $(WTMUX_MCP_SERVER_NAME)
        WTMuxNotificationPrefix: $(WTMUX_NOTIFICATION_PREFIX)
        CFBundleURLTypes:
          - CFBundleURLName: $(PRODUCT_BUNDLE_IDENTIFIER)
            CFBundleURLSchemes:
              - $(WTMUX_URL_SCHEME)
        UTExportedTypeDeclarations:
          - UTTypeIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER).worktree-reference
            UTTypeDescription: $(WTMUX_DISPLAY_NAME) Worktree Reference
            UTTypeConformsTo:
              - public.data
            UTTypeTagSpecification: {}
    entitlements:
      path: WTMux/WTMux.entitlements
      properties:
        com.apple.security.app-sandbox: false
    postBuildScripts:
      - name: "Build and embed wtmux-mcp"
        basedOnDependencyAnalysis: false
        script: |
          if [ "$CONFIGURATION" = "Release" ]; then
            SWIFT_CONFIG="release"
          else
            SWIFT_CONFIG="debug"
          fi
          swift build --package-path "$SRCROOT/Packages/WTMCP" -c $SWIFT_CONFIG 2>&1
          cp -f "$SRCROOT/Packages/WTMCP/.build/$SWIFT_CONFIG/wtmux-mcp" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-mcp"
          codesign --force --sign - "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-mcp"
      - name: "Build and embed wtmux-hook"
        basedOnDependencyAnalysis: false
        script: |
          if [ "$CONFIGURATION" = "Release" ]; then
            SWIFT_CONFIG="release"
          else
            SWIFT_CONFIG="debug"
          fi
          swift build --package-path "$SRCROOT/Packages/WTHook" -c $SWIFT_CONFIG 2>&1
          cp -f "$SRCROOT/Packages/WTHook/.build/$SWIFT_CONFIG/wtmux-hook" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-hook"
          codesign --force --sign - "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-hook"

  WTMux-Stable:
    type: application
    platform: macOS
    sources:
      - path: WTMux
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grahampark.wtmux.stable
        PRODUCT_NAME: "Stable"
        WTMUX_DISPLAY_NAME: Stable
        WTMUX_STORE_NAME: WTMuxStable
        WTMUX_URL_SCHEME: wtmux-stable
        WTMUX_MCP_SERVER_NAME: wtmux-stable
        WTMUX_NOTIFICATION_PREFIX: com.grahampark.wtmux.stable
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 6.0
        ENABLE_PREVIEWS: YES
        ENABLE_APP_SANDBOX: NO
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
        SWIFT_STRICT_CONCURRENCY: complete
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        COMBINE_HIDPI_IMAGES: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: WTCore
      - package: WTTransport
      - package: WTGit
      - package: WTProcess
      - package: WTTerminal
      - package: WTDiff
    info:
      path: WTMux/Info.plist
      properties:
        CFBundleIconFile: AppIcon
        CFBundleName: $(WTMUX_DISPLAY_NAME)
        CFBundleDisplayName: $(WTMUX_DISPLAY_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSApplicationCategoryType: public.app-category.developer-tools
        WTMuxStoreName: $(WTMUX_STORE_NAME)
        WTMuxMCPServerName: $(WTMUX_MCP_SERVER_NAME)
        WTMuxNotificationPrefix: $(WTMUX_NOTIFICATION_PREFIX)
        CFBundleURLTypes:
          - CFBundleURLName: $(PRODUCT_BUNDLE_IDENTIFIER)
            CFBundleURLSchemes:
              - $(WTMUX_URL_SCHEME)
        UTExportedTypeDeclarations:
          - UTTypeIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER).worktree-reference
            UTTypeDescription: $(WTMUX_DISPLAY_NAME) Worktree Reference
            UTTypeConformsTo:
              - public.data
            UTTypeTagSpecification: {}
    entitlements:
      path: WTMux/WTMux.entitlements
      properties:
        com.apple.security.app-sandbox: false
    postBuildScripts:
      - name: "Build and embed wtmux-mcp"
        basedOnDependencyAnalysis: false
        script: |
          if [ "$CONFIGURATION" = "Release" ]; then
            SWIFT_CONFIG="release"
          else
            SWIFT_CONFIG="debug"
          fi
          swift build --package-path "$SRCROOT/Packages/WTMCP" -c $SWIFT_CONFIG 2>&1
          cp -f "$SRCROOT/Packages/WTMCP/.build/$SWIFT_CONFIG/wtmux-mcp" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-mcp"
          codesign --force --sign - "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-mcp"
      - name: "Build and embed wtmux-hook"
        basedOnDependencyAnalysis: false
        script: |
          if [ "$CONFIGURATION" = "Release" ]; then
            SWIFT_CONFIG="release"
          else
            SWIFT_CONFIG="debug"
          fi
          swift build --package-path "$SRCROOT/Packages/WTHook" -c $SWIFT_CONFIG 2>&1
          cp -f "$SRCROOT/Packages/WTHook/.build/$SWIFT_CONFIG/wtmux-hook" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-hook"
          codesign --force --sign - "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/wtmux-hook"

schemes:
  WTMux:
    build:
      targets:
        WTMux: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  WTMux-Stable:
    build:
      targets:
        WTMux-Stable: all
    run:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
